Resources:
  ClearLambdaStorage:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: !Sub QBI-${environment}-ClearLambdaStorage
      CodeUri: .
      Handler: functions.utils.handler.clear_lambda_storage
      Role: !Sub "{{resolve:ssm:${tfExportPrefix}/lambda/ClearLambda/iamRole}}"
      Tags:
        Name: !Sub QBI-${environment}-ClearLambdaStorage
    
  InvokeClearLambdaEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: InvokeClearLambdaEventRule
      ScheduleExpression: cron(0 12 ? * SUN *) # Run every sunday at 12:00pm UTC
      State: ENABLED
      Targets:
        - Arn: !GetAtt ClearLambdaStorage.Arn
          Id: TargetFunction     
